{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pinot.controller.fullname" . }}-jmx-config
  labels:
    app: {{ include "pinot.name" . }}
    chart: {{ include "pinot.chart" . }}
    component: {{ .Values.controller.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  prometheus-pinot-controller.yml: |-
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.controller.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    rules:
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controllercontroller(\\w+)\"><>(\\w+)"
        name: "pinot_controller_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controllerhelix\\.(\\w+)\"><>(\\w+)"
        name: "pinot_controller_helix_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controllerhelixZookeeperReconnects\"><>(\\w+)"
        name: "pinot_controller_helix_ZookeeperReconnects_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controlleridealstateZnodeSize.(\\w+)_(\\w+)\"><>(\\w+)"
        name: "pinot_controller_idealstateZnodeSize_$3"
        labels:
          table: "$1"
          tableType: "$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controllernumberOfReplicas.(\\w+)_(\\w+)\"><>(\\w+)"
        name: "pinot_controller_numberOfReplicas_$3"
        labels:
          table: "$1"
          tableType: "$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controllerpercentOfReplicas.(\\w+)_(\\w+)\"><>(\\w+)"
        name: "pinot_controller_percentOfReplicas_$3"
        labels:
          table: "$1"
          tableType: "$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controllerpercentSegmentsAvailable.(\\w+)_(\\w+)\"><>(\\w+)"
        name: "pinot_controller_percentSegmentsAvailable_$3"
        labels:
          table: "$1"
          tableType: "$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controllersegmentCount.(\\w+)_(\\w+)\"><>(\\w+)"
        name: "pinot_controller_segmentCount_$3"
        labels:
          table: "$1"
          tableType: "$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controllersegmentsInErrorState.(\\w+)_(\\w+)\"><>(\\w+)"
        name: "pinot_controller_segmentsInErrorState_$3"
        labels:
          table: "$1"
          tableType: "$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controllernumberSegmentUploadTimeoutExceeded\"><>(\\w+)"
        name: "pinot_controller_numberSegmentUploadTimeoutExceeded_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controllernumberTimesScheduleTasksCalled\"><>(\\w+)"
        name: "pinot_controller_numberTimesScheduleTasksCalled_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controllerperiodicTaskNumTablesProcessed.(\\w+)\"><>(\\w+)"
        name: "pinot_controller_periodicTaskNumTablesProcessed_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controllerpinotControllerLeader\"><>(\\w+)"
        name: "pinot_controller_pinotControllerLeader_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controllerpinotControllerPartitionLeader.(\\w+)\"><>(\\w+)"
        name: "pinot_controller_partitionLeader_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controllerrealtimeTableCount\"><>(\\w+)"
        name: "pinot_controller_realtimeTableCount_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ValidationMetrics\", name=\"pinot.controller.(\\w+)\\.(\\w+)\"><>(\\w+)"
        name: "pinot_controller_validateion_$2_$3"
        labels:
          table: "$1"
      - pattern: "java.lang<name=CodeHeap 'non-nmethods', type=MemoryPool><>(\\w+)"
        name: "java_lang_codeheap_non_nmethods_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'non-nmethods', type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_codeheap_non_nmethods_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'non-profiled nmethods', type=MemoryPool><>(\\w+)"
        name: "java_lang_codeheap_non_profiled_nmethods_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'non-profiled nmethods', type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_codeheap_non_profiled_nmethods_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'profiled nmethods', type=MemoryPool><>(\\w+)"
        name: "java_lang_codeheap_profiled_nmethods_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'profiled nmethods', type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_codeheap_profiled_nmethods_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Compressed Class Space, type=MemoryPool><>(\\w+)"
        name: "java_lang_compressed_class_space_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Compressed Class Space, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_compressed_class_space_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Eden Space, type=MemoryPool><>(\\w+)"
        name: "java_lang_g1_eden_space_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Eden Space, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_g1_eden_space_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Old Gen, type=MemoryPool><>(\\w+)"
        name: "java_lang_g1_old_gen_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Old Gen, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_g1_old_gen_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Survivor Space, type=MemoryPool><>(\\w+)"
        name: "java_lang_g1_survivor_space_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Survivor Space, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_g1_survivor_space_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Metaspace, type=MemoryPool><>(\\w+)"
        name: "java_lang_metaspace_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Metaspace, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_metaspace_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Old Generation, type=GarbageCollector><>(\\w+)"
        name: "java_lang_g1_old_generation_$1"
        labels:
          type: "GarbageCollector"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector, key=CodeHeap 'profiled nmethods'><LastGcInfo, memoryUsageAfterGc>(\\w+)"
        name: "java_lang_g1_young_generation_lastgcinfo_memoryusageaftergc_$1"
        labels:
          type: "GarbageCollector"
          key: "CodeHeap 'profiled nmethods'"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector, key=CodeHeap 'profiled nmethods'><LastGcInfo, memoryUsageBeforeGc>(\\w+)"
        name: "java_lang_g1_young_generation_lastgcinfo_memoryusagebeforegc_$1"
        labels:
          type: "GarbageCollector"
          key: "CodeHeap 'profiled nmethods'"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector><>(\\w+)"
        name: "java_lang_g1_young_generation_$1"
        labels:
          type: "GarbageCollector"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector><(\\w+)>(\\w+)"
        name: "java_lang_g1_young_generation_$1_$2"
        labels:
          type: "GarbageCollector"
      - pattern: "java.lang<type=ClassLoading><>(\\w+)"
        name: "java_lang_classloading_$1"
      - pattern: "java.lang<type=Memory><(\\w+)>(\\w+)"
        name: "java_lang_memory_$1_$2"
      - pattern: "java.lang<type=OperatingSystem><>(\\w+)"
        name: "java_lang_operatingsystem_$1"
      - pattern: "java.lang<type=Threading><>(\\w+)"
        name: "java_lang_threading_$1"
      - pattern: "java.nio<name=direct, type=BufferPool><>(\\w+)"
        name: "java_nio_direct_$1"
        labels:
          type: "BufferPool"
      - pattern: "java.nio<name=mapped, type=BufferPool><>(\\w+)"
        name: "java_nio_mapped_$1"
        labels:
          type: "BufferPool"
{{- end }}
