{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PrometheusRule" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "pinot.name" . }}-prometheus-rule
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "pinot.name" . }}
    chart: {{ include "pinot.chart" . }}
    component: {{ .Values.controller.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    monitoring: shared
spec:
  groups:
  - name: pinot
    rules:
    - alert: PinotErrorSegments
      annotations:
        summary: 'Pinot segments in Error state'
        message: '{{ $value }} segments in table {{ $labels.table }} are in Error state'
      expr: sum by(pod, table, tabletype) (pinot_controller_segmentsinerrorstate_value) > 0
      for: 10s
      labels:
        severity: critical
        productgroup: platform-infrastructure
{{- end }}
