{{- if .Values.minion.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pinot.minion.fullname" . }}-log-config
  labels:
    app: {{ include "pinot.name" . }}
    chart: {{ include "pinot.chart" . }}
    component: {{ .Values.minion.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pinot-minion-log4j2.xml: |-
    <Configuration monitorInterval="30">
      <Appenders>
        <Console name="console" target="SYSTEM_OUT">
          <PatternLayout>
            <pattern>%d{yyyy/MM/dd HH:mm:ss.SSS} %p [%c{1.}] [%t] %m%n</pattern>
          </PatternLayout>
        </Console>
      </Appenders>
      <Loggers>
        <Root level={{ .Values.minion.logging.level | quote }} additivity="false">
          <AppenderRef ref="console"/>
        </Root>
        <AsyncLogger name="org.reflections" level="error" additivity="false">
          <AppenderRef ref="console"/>
        </AsyncLogger>
      </Loggers>
    </Configuration>
{{- end }}
