{{- if .Values.server.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pinot.server.fullname" . }}-config
  labels:
    app: {{ include "pinot.name" . }}
    chart: {{ include "pinot.chart" . }}
    component: {{ .Values.server.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pinot-server.conf: |-
    pinot.server.netty.port={{ .Values.server.ports.netty }}
    pinot.server.adminapi.port={{ .Values.server.ports.admin }}
    pinot.server.instance.dataDir={{ .Values.server.dataDir }}
    pinot.server.instance.segmentTarDir={{ .Values.server.segmentTarDir }}
    pinot.set.instance.id.to.hostname=true
    pinot.server.instance.realtime.alloc.offheap=true
    pinot.server.query.executor.timeout=60000
    {{- if eq .Values.cluster.storage.scheme "gs" }}
    pinot.server.instance.enable.split.commit=true
    pinot.server.storage.factory.class.gs=org.apache.pinot.plugin.filesystem.GcsPinotFS
    pinot.server.storage.factory.gs.projectId={{ .Values.cluster.storage.gs.projectId }}
    pinot.server.storage.factory.gs.gcpKey={{ .Values.cluster.storage.gs.gcpKey }}
    pinot.server.segment.fetcher.protocols=file,http,gs
    pinot.server.segment.fetcher.gs.class=org.apache.pinot.common.utils.fetcher.PinotFSSegmentFetcher
    {{- end }}
    {{- if eq .Values.cluster.storage.scheme "s3" }}
    pinot.server.storage.factory.class.s3=org.apache.pinot.plugin.filesystem.S3PinotFS
    pinot.server.storage.factory.s3.region={{ .Values.cluster.storage.s3.region }}
    pinot.server.segment.fetcher.protocols=file,http,s3
    pinot.server.segment.fetcher.s3.class=org.apache.pinot.common.utils.fetcher.PinotFSSegmentFetcher
    pinot.controller.storage.factory.s3.disableAcl=false
    {{- end }}
{{- end }}
