{{- if .Values.server.enabled }}
{{- range $name,$tierConfig := omit .Values.server.tiers "default" }}
{{- $tier := mergeOverwrite (deepCopy (omit $.Values.server "tiers")) (deepCopy $.Values.server.tiers.default) (deepCopy $tierConfig) }}
{{- if $tier.podDisruptionBudget.enabled }}
---
{{- if $.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  {{- if eq $name "tier1" }}
  name: {{ include "pinot.server.fullname" $ }}
  {{- else }}
  name: {{ include "pinot.server.fullname" $ }}-{{ $name }}
  {{- end }}
  labels:
    app: {{ include "pinot.name" $ }}
    chart: {{ include "pinot.chart" $ }}
    {{- if eq $name "tier1" }}
    component: {{ $.Values.server.name }}
    {{- else }}
    component: {{ $.Values.server.name }}-{{ $name }}
    {{- end }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  {{- if $tier.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $tier.podDisruptionBudget.minAvailable }}
  {{- end  }}
  {{- if $tier.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $tier.podDisruptionBudget.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      app: {{ include "pinot.name" $ }}
      release: {{ $.Release.Name }}
      {{- if eq $name "tier1" }}
      component: {{ $.Values.server.name }}
      {{- else }}
      component: {{ $.Values.server.name }}-{{ $name }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
