{{- if .Values.server.enabled }}
{{- range $name,$tierConfig := omit .Values.server.tiers "default" }}
{{- $tier := mergeOverwrite (deepCopy (omit $.Values.server "tiers")) (deepCopy $.Values.server.tiers.default) (deepCopy $tierConfig) }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if eq $name "tier1" }}
  name: {{ include "pinot.server.fullname" $ }}
  {{- else }}
  name: {{ include "pinot.server.fullname" $ }}-{{ $name }}
  {{- end }}
  labels:
    app: {{ include "pinot.name" $ }}
    chart: {{ include "pinot.chart" $ }}
    {{- if eq $name "tier1" }}
    component: {{ $.Values.server.name }}
    {{- else }}
    component: {{ $.Values.server.name }}-{{ $name }}
    {{- end }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http-netty
      port: {{ $tier.ports.netty }}
      protocol: TCP
      targetPort: http-netty
    - name: http-admin
      port: {{ $tier.ports.admin }}
      protocol: TCP
      targetPort: http-admin
    - name: grpc
      port: {{ $tier.ports.grpc }}
      protocol: TCP
      targetPort: grpc
  selector:
    app: {{ include "pinot.name" $ }}
    release: {{ $.Release.Name }}
    {{- if eq $name "tier1" }}
    component: {{ $.Values.server.name }}
    {{- else }}
    component: {{ $.Values.server.name }}-{{ $name }}
    {{- end }}
{{- end }}
{{- end }}
