{{- if .Values.server.enabled }}
{{- range $name,$tierConfig := omit .Values.server.tiers "default" }}
{{- $tier := mergeOverwrite (omit $.Values.server "tiers") $.Values.server.tiers.default $tierConfig }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if eq $name "tier1" }}
  name: {{ include "pinot.server.fullname" $ }}-svc
  {{- else }}
  name: {{ include "pinot.server.fullname" $ }}-{{ $name }}-svc
  {{- end }}
  labels:
    app: {{ include "pinot.name" $ }}
    chart: {{ include "pinot.chart" $ }}
    {{- if eq $name "tier1" }}
    component: {{ $.Values.server.name }}
    {{- else }}
    component: {{ $.Values.server.name }}-{{ $name }}
    {{- end }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: request
      port: {{ $tier.ports.netty }}
    {{- if $tier.prometheus.jmx.enabled }}
    - name: prometheus-jmx
      port: {{ $tier.prometheus.jmx.port }}
    {{- end }}
  selector:
    app: {{ include "pinot.name" $ }}
    release: {{ $.Release.Name }}
    {{- if eq $name "tier1" }}
    component: {{ $tier.name }}
    {{- else }}
    component: {{ $tier.name }}-{{ $name }}
    {{- end }}
{{- end }}
{{- end }}
