{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( .Values.server.enabled ) }}
{{- range $name,$tierConfig := omit .Values.server.tiers "default" }}
{{- $tier := mergeOverwrite (omit $.Values.server "tiers") $.Values.server.tiers.default $tierConfig }}
{{- if and ( $tier.prometheus.jmx.enabled ) ( $tier.servicemonitor.enabled ) }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  {{- if eq $name "tier1" }}
  name: {{ include "pinot.server.fullname" $ }}
  {{- else }}
  name: {{ include "pinot.server.fullname" $ }}-{{ $name }}
  {{- end }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ include "pinot.name" $ }}
    chart: {{ include "pinot.chart" $ }}
    {{- if eq $name "tier1" }}
    component: {{ $.Values.server.name }}
    {{- else }}
    component: {{ $.Values.server.name }}-{{ $name }}
    {{- end }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    monitoring: shared
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - {{ include "pinot.name" $ }}
      - key: release
        operator: In
        values:
          - {{ $.Release.Name }}
      - key: component
        operator: In
        values:
          {{- if eq $name "tier1" }}
          - {{ $.Values.server.name }}
          {{- else }}
          - {{ $.Values.server.name }}-{{ $name }}
          {{- end }}
  endpoints:
    - port: prometheus-jmx
      interval: {{ $tier.servicemonitor.interval }}
      {{- if $tier.servicemonitor.secure }}
      scheme: https
      tlsConfig:
        {{- toYaml $tier.servicemonitor.tlsConfig | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
