{{- if .Values.server.enabled }}
{{- range $name,$tierConfig := omit .Values.server.tiers "default" }}
{{- $tier := mergeOverwrite (deepCopy (omit $.Values.server "tiers")) (deepCopy $.Values.server.tiers.default) (deepCopy $tierConfig) }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if eq $name "tier1" }}
  name: {{ include "pinot.server.fullname" $ }}-svc
  {{- else }}
  name: {{ include "pinot.server.fullname" $ }}-{{ $name }}-svc
  {{- end }}
  labels:
    app: {{ include "pinot.name" $ }}
    chart: {{ include "pinot.chart" $ }}
    {{- if eq $name "tier1" }}
    component: {{ $.Values.server.name }}
    {{- else }}
    component: {{ $.Values.server.name }}-{{ $name }}
    {{- end }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: request
      port: {{ $tier.ports.netty }}
      protocol: TCP
      targetPort: request
    - name: http-admin
      port: {{ $tier.ports.admin }}
      protocol: TCP
      targetPort: http-admin
    - name: grpc
      port: {{ $tier.ports.grpc }}
      protocol: TCP
      targetPort: grpc
    {{- if $tier.prometheus.jmx.enabled }}
    - name: http-metrics
      port: {{ $tier.prometheus.jmx.port }}
      protocol: TCP
      targetPort: http-metrics
    {{- end }}
  selector:
    app: {{ include "pinot.name" $ }}
    release: {{ $.Release.Name }}
    {{- if eq $name "tier1" }}
    component: {{ $tier.name }}
    {{- else }}
    component: {{ $tier.name }}-{{ $name }}
    {{- end }}
{{- end }}
{{- end }}
