{
 "title": "Pinot Dashboard",
 "tags": [ "traceable" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Pinot Segment Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pinot_controller_segmentcount_value) by (table, tabletype)",
     "legendFormat": "{{table}}_{{tabletype}}"
    }
   ]
  },
  {
   "title": "Pinot Total Document Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pinot_server_documentcount_value) by (table, tabletype)",
     "legendFormat": "{{table}}_{{tabletype}}"
    }
   ]
  },
  {
   "title": "Pinot Num of Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pinot_controller_numberofreplicas_value) by (pod, table, tabletype) >= 0",
     "legendFormat": "{{table}}_{{tabletype}}"
    }
   ]
  },
  {
   "title": "Pinot Percent of Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(pinot_controller_percentofreplicas_value) by (pod, table, tabletype) >= 0",
     "legendFormat": "{{table}}_{{tabletype}}"
    }
   ]
  },
  {
   "title": "Pinot Idealstate Znode Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(pinot_controller_idealstateznodesize_value) by (table, tabletype)",
     "legendFormat": "{{table}}_{{tabletype}}"
    }
   ]
  },
  {
   "title": "Pinot Error Segment Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pinot_controller_segmentsinerrorstate_value) by (pod, table, tabletype) >= 0",
     "legendFormat": "{{table}}_{{tabletype}}"
    }
   ]
  },
  {
   "title": "Pinot Query QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pinot_broker_queryexecution_count [1m])) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Pinot Query Execution Latency P99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pinot_broker_queryexecution_99thpercentile[1m])) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Pinot Query Documents Scanned Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pinot_broker_documentsscanned_count [1m])) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Pinot Realtime Consuming Rows Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pinot_server_realtimerowsconsumed_count[1m])) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Pinot Realtime Freshness Lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(pinot_server_freshnesslagms_99thpercentile) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Pinot MMAP Buffer Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(pinot_server_memory_mmapbufferusage_value) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pinot Server Schedule Wait Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pinot_server_schedulerwait_99thpercentile) by (table, tabletype)",
     "legendFormat": "{{table}}-{{tabletype}}"
    }
   ]
  },
  {
   "title": "Pinot server off heap memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pinot_server_realtime_offheapmemoryused_value)  by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pinot server heap memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{pod=~\"pinot-server-.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pinot Controller Leader",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pinot_controller_helix_leader_value) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}