#!/bin/sh
# HEALTHCHECK for use in `docker ps` or `docker-compose ps`.
# It can also be used as a readiness probe in k8s

# Fail on unset variables, but don't quit on rc!=0, so we can log what happened
set -u +e

IP="$(hostname -i || echo '127.0.0.1')"

nc -z ${IP} 8097 > /dev/null 2>&1
SERVER_RC=$?
if [ "$SERVER_RC" == "0" ]; then
  nc -z ${IP} 9000 > /dev/null 2>&1
  BROKER_RC=$?
  if [ "$BROKER_RC" == "0" ]; then
    exit 0
  fi

  echo Pinot Broker port check failed with code: $BROKER_RC
  exit 1
fi

echo Pinot Server port check failed with code: $SERVER_RC
exit 1
