#!/bin/sh
# HEALTHCHECK for use in `docker ps` or `docker-compose ps`.
# It can also be used as a readiness probe in k8s

# Fail on unset variables, but don't quit on rc!=0, so we can log what happened
set -u +e

IP="$(hostname -i || echo '127.0.0.1')"

HEALTH_OUT=$(wget -qO- http://${IP}:7098/health 2>&1)
HEALTH_RC=$?
if [ "$HEALTH_RC" == "0" ]; then
  exit 0
fi

echo Pinot health check failed with output: ${HEALTH_OUT}
exit 1
