#!/bin/sh
# HEALTHCHECK for use in `docker ps` or `docker-compose ps`.
# It can also be used as a readiness probe in k8s

# Fail on unset variables, but don't quit on rc!=0, so we can log what happened
set -u +e

IP="$(hostname -i || echo '127.0.0.1')"

wget -qO- http://${IP}:7098/health > /dev/null 2>&1
HEALTH_RC=$?
if [ "$HEALTH_RC" == "0" ]; then
  # install-schema deletes the schemas directory on completion
  test -d schemas
  SCHEMA_RC=$?
  if [ "$SCHEMA_RC" == "0" ]; then
    exit 0
  fi

  echo Pinot schema installation is not complete
  exit 1
fi

echo Pinot health check failed with code: $HEALTH_RC
exit 1
