#!/bin/sh
# ENTRYPOINT script that starts Pinot
#
# This intentionally locates config using the current working directory, in order to consolidate
# Dockerfile instructions to WORKDIR
set -eu

# Default variables so that the script doesn't bomb out on absence
JAVA_OPTS=${JAVA_OPTS:-"-Xms256M -Xmx512M -XX:+ExitOnOutOfMemoryError"}
ZK_ADDRESS=${ZK_ADDRESS:-zookeeper:2181}

# Apply one-time deferred configuration that relies on ENV variables
#
# TODO: Revert this when relative paths are allowed
#         https://github.com/apache/incubator-pinot/issues/5975
CONTROLLER_CONF=./etc/pinot-controller.conf
CONTROLLER_DATA_DIR=controller.data.dir=$PWD/data/controller
CONTROLLER_ZK_STR=controller.zk.str=${ZK_ADDRESS}
for line in $CONTROLLER_DATA_DIR $CONTROLLER_ZK_STR
do
  grep -qF -- $line $CONTROLLER_CONF || echo $line >> $CONTROLLER_CONF
done
#
SERVER_CONF=./etc/pinot-server.conf
SERVER_DATA_DIR=pinot.server.instance.dataDir=$PWD/data/server/index
SERVER_SEGMENT_TAR_DIR=pinot.server.instance.segmentTarDir=$PWD/data/server/segment
for line in $SERVER_DATA_DIR $SERVER_SEGMENT_TAR_DIR
do
  grep -qF -- $line $SERVER_CONF || echo $line >> $SERVER_CONF
done

# Try to install schemas while service is coming up
test -d schemas && install-schema &

echo Starting Pinot Service Manager
# TODO: link to pinot issue why we need internal access
exec java \
  --add-opens java.base/jdk.internal.ref=ALL-UNNAMED \
  -classpath 'classes:libs/*' \
  $JAVA_OPTS \
  -Dlog4j.configurationFile=etc/log4j2.properties \
  -Dapp.name=pinot-admin \
  -Dapp.pid=$$ \
  -Dapp.home=$PWD \
  -Dbasedir=$PWD \
  org.apache.pinot.tools.admin.PinotAdministrator \
  StartServiceManager -clusterName hypertrace-views \
  -zkAddress $ZK_ADDRESS -port 7098 \
  -bootstrapConfigPaths etc/pinot-controller.conf etc/pinot-broker.conf etc/pinot-server.conf
