#!/bin/sh
# ENTRYPOINT script that starts Pinot
#
# This intentionally locates config using the current working directory, in order to consolidate
# Dockerfile instructions to WORKDIR
set -eu

echo Starting Pinot Service Manager
# TODO: link to pinot issue why we need internal access
exec java \
  --add-opens java.base/jdk.internal.ref=ALL-UNNAMED \
  -classpath $PINOT_HOME/classes \
  $JAVA_OPTS \
  -Dlog4j.configurationFile=etc/log4j2.properties \
  -Dapp.name=pinot-admin \
  -Dapp.pid=$$ \
  -Dapp.home=$PINOT_HOME \
  -Dbasedir=$PINOT_HOME \
  org.apache.pinot.tools.admin.PinotAdministrator \
  StartServiceManager -clusterName hypertrace-views \
  -zkAddress zookeeper:2181 -port 7098 \
  -bootstrapConfigPaths $PINOT_HOME/etc/pinot-controller.conf $PINOT_HOME/etc/pinot-broker.conf $PINOT_HOME/etc/pinot-server.conf
