{{- if .Values.servicemanager.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pinot.servicemanager.fullname" . }}-log-config
  labels:
    app: {{ include "pinot.name" . }}
    chart: {{ include "pinot.chart" . }}
    component: {{ .Values.servicemanager.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pinot-servicemanager-log4j2.xml: |-
    <Configuration monitorInterval="30">
      <Appenders>
        <Console name="console" target="SYSTEM_OUT">
          <PatternLayout>
            <pattern>%d{yyyy/MM/dd HH:mm:ss.SSS} %p [%c{1.}] [%t] %m%n</pattern>
          </PatternLayout>
        </Console>
      </Appenders>
      <Loggers>
        <Root level={{ .Values.servicemanager.logging.level | quote }} additivity="false">
          <AppenderRef ref="console"/>
        </Root>
        <AsyncLogger name="org.reflections" level="error" additivity="false">
          <AppenderRef ref="console"/>
        </AsyncLogger>
        <Logger name="org.apache.pinot.shaded.org.apache.kafka" level="error" additivity="false">
          <AppenderRef ref="console"/>
        </Logger>
        <Logger name="org.apache.pinot.broker.querylog.QueryLogger" level="info" additivity="false">
            <AppenderRef ref="console"/>
        </Logger>
      </Loggers>
    </Configuration>
{{- end }}
