{{- if .Values.servicemanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pinot.servicemanager.fullname" . }}
  labels:
    app: {{ include "pinot.name" . }}
    chart: {{ include "pinot.chart" . }}
    component: {{ .Values.servicemanager.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - name: servicemanager
      port: {{ .Values.servicemanager.service.port }}
    - name: controller
      port: {{ .Values.controller.service.port }}
    - name: server-netty
      port: {{ .Values.server.ports.netty }}
    - name: broker
      port: {{ .Values.broker.service.port }}
    {{- if .Values.servicemanager.minion.enabled }}
    - name: minion
      port: {{ .Values.minion.service.port }}
    {{- end }}
  selector:
    app: {{ include "pinot.name" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.servicemanager.name }}
{{- end }}
