fullnameOverride: ""
nameOverride: ""

image:
  repository: hypertrace/pinot
  pullPolicy: IfNotPresent
  tagOverride: ""

imagePullSecrets: []

cluster:
  name: pinot
  storage:
    scheme: file

controller:
  name: controller
  component: controller
  enabled: true
  port: 9000
  replicaCount: 1

  vip:
    enabled: false

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2Gi
    mountPath: /var/pinot/controller/data
    storageClass: "standard"

  data:
    dir: /var/pinot/controller/data

  local:
    temp:
      dir: /var/pinot/controller/data/temp

  jvmOpts: "-Xms128M -Xmx320M"

  log4j2ConfFile: /opt/pinot/conf/pinot-controller-log4j2.xml
  pluginsDir: /opt/pinot/plugins

  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
    port: 9000
    nodePort: ""

  external:
    enabled: false
    type: LoadBalancer
    port: 9000

  resources:
    requests:
      cpu: "0.1"
      memory: 400Mi

  podLabels: {}

  podAnnotations: {}

  updateStrategy:
    type: RollingUpdate

  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3

  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3

  nodeSelector: {}

  tolerations: []

  affinity: {}

  securityContext: {}

  serviceAccount:
    create: true
    name: ""

  terminationGracePeriodSeconds: 30

  servicemonitor:
    enabled: false
    interval: 15s
    secure: false
    tlsConfig: {}

  podDisruptionBudget:
    enabled: false
    maxUnavailable: 1
    minAvailable: ""

  jmx:
    enabled: false
    port: 7022
    opts: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=7022 -Dcom.sun.management.jmxremote.rmi.port=7022 -Djava.rmi.server.hostname=127.0.0.1"

  prometheus:
    jmx:
      enabled: false
      port: 7071
      image:
        repository: solsson/kafka-prometheus-jmx-exporter@sha256
        tag: 6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "0.25"
          memory: "256Mi"

  storageclass:
    enabled: false
    name: pinot-controller
    annotations: {}
    provisioner: kubernetes.io/gce-pd
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    parameters:
      type: pd-standard

  dashboard:
    enabled: false
    namespace: monitoring

broker:
  name: broker
  enabled: true
  port: 8099
  replicaCount: 1

  timeoutMs: 60000

  jvmOpts: "-Xms128M -Xmx320M"

  log4j2ConfFile: /opt/pinot/conf/pinot-broker-log4j2.xml
  pluginsDir: /opt/pinot/plugins

  routingTable:
    builderClass: random

  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
    port: 8099
    nodePort: ""

  external:
    enabled: false
    type: LoadBalancer
    port: 8099

  resources:
    requests:
      cpu: "0.1"
      memory: 400Mi

  podLabels: {}

  podAnnotations: {}

  updateStrategy:
    type: RollingUpdate

  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3

  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3

  nodeSelector: {}

  affinity: {}

  tolerations: []

  securityContext: {}

  serviceAccount:
    create: true
    name: ""

  terminationGracePeriodSeconds: 30

  servicemonitor:
    enabled: false
    interval: 15s
    secure: false
    tlsConfig: {}

  podDisruptionBudget:
    enabled: false
    maxUnavailable: 1
    minAvailable: ""

  jmx:
    enabled: false
    port: 7022
    opts: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=7022 -Dcom.sun.management.jmxremote.rmi.port=7022 -Djava.rmi.server.hostname=127.0.0.1"

  prometheus:
    jmx:
      enabled: false
      port: 7071
      image:
        repository: solsson/kafka-prometheus-jmx-exporter@sha256
        tag: 6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "0.25"
          memory: "256Mi"

server:
  name: server
  enabled: true

  ports:
    netty: 8098
    admin: 8097

  replicaCount: 1

  dataDir: /var/pinot/server/data/index
  segmentTarDir: /var/pinot/server/data/segment

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2Gi
    mountPath: /var/pinot/server/data
    storageClass: "standard"

  jvmOpts: "-Xms128M -Xmx320M"

  log4j2ConfFile: /opt/pinot/conf/pinot-server-log4j2.xml
  pluginsDir: /opt/pinot/plugins

  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
    nodePort: ""

  resources:
    requests:
      cpu: "0.1"
      memory: 400Mi

  podLabels: {}

  podAnnotations: {}

  updateStrategy:
    type: RollingUpdate

  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3

  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3

  nodeSelector: {}

  affinity: {}

  tolerations: []

  securityContext: {}

  serviceAccount:
    create: true
    name: ""

  terminationGracePeriodSeconds: 30

  servicemonitor:
    enabled: false
    interval: 15s
    secure: false
    tlsConfig: {}

  podDisruptionBudget:
    enabled: false
    maxUnavailable: 1
    minAvailable: ""

  jmx:
    enabled: false
    port: 7022
    opts: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=7022 -Dcom.sun.management.jmxremote.rmi.port=7022 -Djava.rmi.server.hostname=127.0.0.1"

  prometheus:
    jmx:
      enabled: false
      port: 7071
      image:
        repository: solsson/kafka-prometheus-jmx-exporter@sha256
        tag: 6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "0.25"
          memory: "256Mi"

  storageclass:
    enabled: false
    name: pinot-server
    annotations: {}
    provisioner: kubernetes.io/gce-pd
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    parameters:
      type: pd-standard


servicemanager:
  name: servicemanager
  enabled: false
  port: 9090
  replicaCount: 1
  image:
    repository: apachepinot/pinot
    tag: 0.5.0-SNAPSHOT-01cdc55f5-20200617
    sha256: 332c6d7052a2e2f045513647b4bea2119a881718e5e4bbb34100af4761af5137

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2Gi
    mountPath: /var/pinot/servicemanager/data
    storageClass: "standard"

  data:
    dir: /var/pinot/servicemanager/data

  jvmOpts: "-Xms128M -Xmx320M"

  log4j2ConfFile: /opt/pinot/conf/pinot-servicemanager-log4j2.xml
  pluginsDir: /opt/pinot/plugins

  service:
    enabled: true
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
    port: 9090
    nodePort: ""

  resources:
    requests:
      cpu: "0.1"
      memory: 400Mi

  podLabels: {}

  podAnnotations: {}

  updateStrategy:
    type: RollingUpdate

  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3

  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3

  nodeSelector: {}

  tolerations: []

  affinity: {}

  securityContext: {}

  serviceAccount:
    create: true
    name: ""

  terminationGracePeriodSeconds: 30

  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
    minAvailable: ""

zookeeper:
  url: ""
  port: 2181
  path: "/pinot"
  retries: 10
  retryInterval: 5
  image:
    repository: "solsson/kafka"
    tag: "2.1.0@sha256:ac3f06d87d45c7be727863f31e79fbfdcb9c610b51ba9cf03c75a95d602f15e1"
    pullPolicy: IfNotPresent
    pullSecret: ""
