# uses 2.4 so we can use condition: service_healthy
version: "2.4"
services:
  kafka-zookeeper:
    image: hypertrace/kafka-zookeeper:main
    container_name: kafka-zookeeper
    networks:
      default:
        aliases:
          - kafka
          - zookeeper
  # use fixed service and container name 'sut; so our test script can copy/pasta
  sut:
    image: hypertrace/pinot-servicemanager:main
    container_name: sut
    depends_on:
      kafka-zookeeper:
        condition: service_healthy
