{{- if .Values.broker.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pinot.broker.fullname" . }}-jmx-config
  labels:
    app: {{ include "pinot.name" . }}
    chart: {{ include "pinot.chart" . }}
    component: {{ .Values.broker.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  prometheus-pinot-broker.yml: |-
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.broker.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    rules:
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+).authorization\"><>(\\w+)"
        name: "pinot_broker_authorization_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.documentsScanned\"><>(\\w+)"
        name: "pinot_broker_documentsScanned_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.entriesScannedInFilter\"><>(\\w+)"
        name: "pinot_broker_entriesScannedInFilter_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.entriesScannedPostFilter\"><>(\\w+)"
        name: "pinot_broker_entriesScannedPostFilter_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.freshnessLagMs\"><>(\\w+)"
        name: "pinot_broker_freshnessLagMs_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.queries\"><>(\\w+)"
        name: "pinot_broker_queries_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.queryExecution\"><>(\\w+)"
        name: "pinot_broker_queryExecution_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.queryRouting\"><>(\\w+)"
        name: "pinot_broker_queryRouting_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.reduce\"><>(\\w+)"
        name: "pinot_broker_reduce_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.requestCompilation\"><>(\\w+)"
        name: "pinot_broker_requestCompilation_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.scatterGather\"><>(\\w+)"
        name: "pinot_broker_scatterGather_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.totalServerResponseSize\"><>(\\w+)"
        name: "pinot_broker_totalServerResponseSize_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)_(\\w+).groupBySize\"><>(\\w+)"
        name: "pinot_broker_groupBySize_$3"
        labels:
          table: "$1"
          tableType: "$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)_(\\w+).noServingHostForSegment\"><>(\\w+)"
        name: "pinot_broker_noServingHostForSegment_$3"
        labels:
          table: "$1"
          tableType: "$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.healthcheck(\\w+)\"><>(\\w+)"
        name: "pinot_broker_healthcheck_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.helix.(\\w+)\"><>(\\w+)"
        name: "pinot_broker_helix_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.helixZookeeper(\\w+)\"><>(\\w+)"
        name: "pinot_broker_helix_zookeeper_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.nettyConnection(\\w+)\"><>(\\w+)"
        name: "pinot_broker_nettyConnection_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.clusterChangeCheck\"\"><>(\\w+)"
        name: "pinot_broker_clusterChangeCheck_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.proactiveClusterChangeCheck\"><>(\\w+)"
        name: "pinot_broker_proactiveClusterChangeCheck_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)Exceptions\"><>(\\w+)"
        name: "pinot_broker_exceptions_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.routingTableUpdateTime\"><>(\\w+)"
        name: "pinot_broker_routingTableUpdateTime_$1"
      - pattern: "java.lang<name=CodeHeap 'non-nmethods', type=MemoryPool><>(\\w+)"
        name: "java_lang_codeheap_non_nmethods_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'non-nmethods', type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_codeheap_non_nmethods_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'non-profiled nmethods', type=MemoryPool><>(\\w+)"
        name: "java_lang_codeheap_non_profiled_nmethods_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'non-profiled nmethods', type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_codeheap_non_profiled_nmethods_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'profiled nmethods', type=MemoryPool><>(\\w+)"
        name: "java_lang_codeheap_profiled_nmethods_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'profiled nmethods', type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_codeheap_profiled_nmethods_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Compressed Class Space, type=MemoryPool><>(\\w+)"
        name: "java_lang_compressed_class_space_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Compressed Class Space, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_compressed_class_space_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Eden Space, type=MemoryPool><>(\\w+)"
        name: "java_lang_g1_eden_space_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Eden Space, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_g1_eden_space_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Old Gen, type=MemoryPool><>(\\w+)"
        name: "java_lang_g1_old_gen_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Old Gen, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_g1_old_gen_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Survivor Space, type=MemoryPool><>(\\w+)"
        name: "java_lang_g1_survivor_space_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Survivor Space, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_g1_survivor_space_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Metaspace, type=MemoryPool><>(\\w+)"
        name: "java_lang_metaspace_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Metaspace, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_metaspace_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Old Generation, type=GarbageCollector><>(\\w+)"
        name: "java_lang_g1_old_generation_$1"
        labels:
          type: "GarbageCollector"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector, key=CodeHeap 'profiled nmethods'><LastGcInfo, memoryUsageAfterGc>(\\w+)"
        name: "java_lang_g1_young_generation_lastgcinfo_memoryusageaftergc_$1"
        labels:
          type: "GarbageCollector"
          key: "CodeHeap 'profiled nmethods'"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector, key=CodeHeap 'profiled nmethods'><LastGcInfo, memoryUsageBeforeGc>(\\w+)"
        name: "java_lang_g1_young_generation_lastgcinfo_memoryusagebeforegc_$1"
        labels:
          type: "GarbageCollector"
          key: "CodeHeap 'profiled nmethods'"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector><>(\\w+)"
        name: "java_lang_g1_young_generation_$1"
        labels:
          type: "GarbageCollector"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector><(\\w+)>(\\w+)"
        name: "java_lang_g1_young_generation_$1_$2"
        labels:
          type: "GarbageCollector"
      - pattern: "java.lang<type=ClassLoading><>(\\w+)"
        name: "java_lang_classloading_$1"
      - pattern: "java.lang<type=Memory><(\\w+)>(\\w+)"
        name: "java_lang_memory_$1_$2"
      - pattern: "java.lang<type=OperatingSystem><>(\\w+)"
        name: "java_lang_operatingsystem_$1"
      - pattern: "java.lang<type=Threading><>(\\w+)"
        name: "java_lang_threading_$1"
      - pattern: "java.nio<name=direct, type=BufferPool><>(\\w+)"
        name: "java_nio_direct_$1"
        labels:
          type: "BufferPool"
      - pattern: "java.nio<name=mapped, type=BufferPool><>(\\w+)"
        name: "java_nio_mapped_$1"
        labels:
          type: "BufferPool"
{{- end }}
