{{- if and .Values.broker.enabled .Values.broker.podDisruptionBudget.enabled }}
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "pinot.broker.fullname" . }}
  labels:
    app: {{ include "pinot.name" . }}
    chart: {{ include "pinot.chart" . }}
    component: {{ .Values.broker.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.broker.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.broker.podDisruptionBudget.minAvailable }}
  {{- end  }}
  {{- if .Values.broker.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.broker.podDisruptionBudget.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      app: {{ include "pinot.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.broker.name }}
{{- end }}
