{{- if .Values.broker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pinot.broker.fullname" . }}-svc
  labels:
    app: {{ include "pinot.name" . }}
    chart: {{ include "pinot.chart" . }}
    component: {{ .Values.broker.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: request
      port: {{ .Values.broker.service.port }}
    {{- if .Values.broker.prometheus.jmx.enabled }}
    - name: http-metrics
      port: {{ .Values.broker.prometheus.jmx.port }}
    {{- end }}
  selector:
    app: {{ include "pinot.name" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.broker.name }}
{{- end }}
